### ISSUE TITLE
Update: rename `shouldNotBeLoggedIn` to  `isLoggedOut`

### ISSUE THREAD

**Issue by ironhack-edu** [itstheandre/lean-express-gen#17]
Since we already have `isLoggedIn` middleware, as an opposite one we should follow the same naming convention. 

Any thoughts on this one @itstheandre?

**Comment by itstheandre** [comment]
Good catch. I like that. Initially we named it because it was in flow of class. But `isLoggedOut` is a far better name. Fixed 👍
