### ISSUE TITLE
Create a single script to run server and client at the same time

### ISSUE THREAD

**Issue by ironhack-edu** [itstheandre/lean-express-gen#24]
It would be great to add a script to start the express server and react client at the same time.

**Comment by itstheandre** [comment]
Okay, I found a way to do it, using an external package. do you think this is not going to add major overhead? The best way to maintain both consoles would be with another package (something like concurrently) to keep the bootstrapping of the server.

It's a rather quick fix, but just to know if you think this doesnt have the potential to make it confusing.

**Comment by itstheandre** [comment]
@ironhack-edu  do you think its valuable or that it adds unnecessary  complexity with the multiple package.json files and all that

**Comment by ironhack-edu** [comment]
Hey @itstheandre, sorry I missed this message somehow. I think it is worth getting it to the table with instructors and checking their opinion before any work is done. If they don't think this adds value, then no need to proceed. Feel free to post a question to the teachers' channel or if it makes more sense, we can post it. Thank you!
