### ISSUE TITLE
Client dependencies empty from fresh install

### ISSUE THREAD

**Issue by tonkabits** [itstheandre/lean-express-gen#30]
Client dependencies is empty when creating a fresh install.
making 
 `npm start`
 fail.

sys={
node v14.17.0
MacOS  v10.15.7

}

**Comment by itstheandre** [comment]
@tonkabits What is the version of the iron launcher that you are running?

**Comment by tonkabits** [comment]
I ran it with
 `npx install ironlauncher <project name> --auth --fs`
so my guess will be latest?? not sure.

**Comment by itstheandre** [comment]
Hey @tonkabits could you run `npx ironlauncher@latest <project-name> --auth --fs` instead?

And let me know if that works

**Comment by tonkabits** [comment]
Hi @itstheandre,   same result. `{
  "name": "irontest-client",
  "version": "0.1.0",
  "private": true,
  "dependencies": {},
  "devDependencies": {
    "@testing-library/jest-dom": "^5.15.1",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build && echo '/* /index.html 200' | cat >build/_redirects ",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
`

here is the generated client package.json and this is the terminal output

![image](https://user-images.githubusercontent.com/35662685/143283322-88ebf487-9d90-46f0-8758-9f678465fc43.png)

**Comment by tonkabits** [comment]
EDIT: tried other computer. which also fail, updated to Node -v 16+ and then worked, so probably a Node version issue, the easiest workaround is adding the dependencies manually for the client `    "@testing-library/jest-dom": "^5.15.1",
    "@testing-library/react": "^11.2.7",
    "@testing-library/user-event": "^12.8.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.1.2"`
