### ISSUE TITLE
Cannot find module 'fs/promises' with node versions 12.x

### ISSUE THREAD

**Issue by ManishPoduval** [itstheandre/lean-express-gen#32]
![Screen Shot 25-11-2021 at 11 10](https://user-images.githubusercontent.com/21152351/143386138-f332eff2-b261-46f6-9618-0b70f9c7f327.png)

I believe in `src/utils/IO/FsOperationRepo.ts` changing

```
import { mkdir, readFile, stat, writeFile } from "fs/promises";
```

to 

```
import { promises: {mkdir, readFile, stat, writeFile}  } from "fs";
```

would fix it.

Let's also start a process to review hot-fixes rather than going back and forth with deploying new changes @ironhack-edu ? 

Another quick solution would be to have all users upgrade to the latest version of node but it's not and ideal one.

**Comment by itstheandre** [comment]
This dependency issue has been fixed
